### ISSUE TITLE
Interpretation of PLACO output

### ISSUE THREAD

**Issue by lalagkaspn** [RayDebashree/PLACO#1]
Hi! Thank you very much for providing this useful tool to the scientific community! I was wondering if I can have your opinion about the interpretation of the PLACO output. How do you explain the fact that p.placo can be significantly low for SNPs that are not significantly associated with the traits (even having p_values > 0.05) ?

Thank you in advance!

**Comment by RayDebashree** [comment]
Hi, one needs to be careful about interpreting p.placo in such situations. I'd recommend making sure the implicit and explicit assumptions for PLACO are roughly met, and all the necessary QC are done (check https://github.com/RayDebashree/PLACO#notes) before trying to interpret. I'd also suggest looking at individual trait p-values & p.placo for all SNPs in a region around such a SNP with significantly low p.placo but individual trait p>0.05.
